# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jorge Balazs
tagline: Applied Scientist
email: jabalazst@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

    Applied Scientist

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jabalazs.github.io/" # the base hostname & protocol for your site
twitter_username: jabalazst
github_username:  jabalazs
stackoverflow_id: "3941813"
# google_scholar_id: Iqr7zaQAAAAJ
linkedin_username: jorgebalazs
rss: RSS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
    - blog.md
    - publications.md

google_analytics: UA-102428067-1
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
