# Site settings
title: Jorge Balazs
tagline: Ph.D. student at the University of Tokyo
email: jorge@weblab.t.u-tokyo.ac.jp
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jabalazs.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  jabalazs
paginate: 5
future: true

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
plugins: [jekyll-paginate, jekyll-redirect-from]

# Google services
google_analytics: UA-102428067-1
